//#### LAB 6 - DOM MANIPULATION ####
//PART 2: MYSTERY BOX
alert("test");//COMMENT OUT AS SOON AS YOU KNOW YOU ARE CONNECTED!!!!

//LISTEN FOR load EVENT


//'WRAPPER' FUNCTION FOR DOM LOGIC

	//GET DOM ELEMENTS WE'LL NEED


	//====CREATE THE FUNCTIONS WE'LL NEED====
	//FUNCTION TO ASK USER


	//FUNCTION TO CHANGE buttonBox


	//SETUP LISTENERS


//END onload FUNCTION